config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :players
  get 'matches/show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount ActionCable.server => '/cable'
  resources :matches do
    get :card_details, on: :member
    get :details, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/banned_card.rb
class BannedCard < ApplicationRecord
  belongs_to :match
  belongs_to :card
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :card
  belongs_to :team
  belongs_to :player
  belongs_to :match
end

app/models/match.rb
class Match < ApplicationRecord

  has_many :teams_matches
  has_many :teams, through: :teams_matches
  has_many :players, through: :teams
  has_many :decks
  has_many :banned_cards
  has_many :cards, through: :decks
  belongs_to :winner_team, foreign_key: :winner_id,   class_name: 'Team'

  def as_json(opts = nil)
    more = {}
    more[:teams] = teams
    attributes.merge(more)
  end

  def store_deck(data)
    card = Card.find_by_uid(data["card_id"])
    players = self.teams.find_by_id(data["team_id"]).players
    if data["player_id"] == 1
      player = players[0]
    else
      player = players[1]
    end
    self.decks.create(card_id: card.id, team_id: data["team_id"], player_id: player.id)
  end

  def match_links
    'akjds'
  end

  rails_admin do
    # configure :player do
    #   label 'Owner of this ball: '
    # end
    edit do
      exclude_fields :teams_matches, :players
    end
    show do
      field :teams
      field :uuid
      field :match_links do
        pretty_value do
          bindings[:object].teams.map do |team|
            path = bindings[:view].show_path('matches', team_id: team.id).gsub('/admin', '')
            bindings[:view].tag(:a, href: path, target: '_blank') << team.name
          end.join('<br/>').html_safe
        end
      end
      field :players
      field :cards_details do
        pretty_value do
          bindings[:view].tag(:a, href: "/matches/#{bindings[:object].id}/card_details", target: '_blank', title: 'cards') << "Cards"
        end
      end
    end
  end

  def cards_details
    'fdfd'
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
  has_many :decks
  has_many :cards, through: :decks
end

app/models/team.rb
class Team < ApplicationRecord

	has_many :teams_matches, dependent: :destroy
	has_many :matches, through: :teams_matches
  has_many :players
  has_many :decks
  has_many :cards, through: :decks

	# after_create_commit { MessageBroadcastJob.perform_later(self) }
  def as_json(opts = nil)
    more = {}
    more[:players] = players
    attributes.merge(more)
  end
end

app/models/teams_match.rb
class TeamsMatch < ApplicationRecord
  belongs_to :match
  belongs_to :team
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def show
    @match = Match.find(params[:id])
    @team = @match.teams.find_by(id: params[:team_id])
    if @team.blank?
      render text: '<h3>Team not found</h3>', layout: false
    end
  end

  def card_details
    @match = Match.find(params[:id])
    @decks = @match.decks.group_by(&:team)
  end

  def details
    @match = Match.find(params[:id])
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :contact_number, :team_id, :nick_name)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>CS Leaderboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css"> -->
    <!-- <link rel="stylesheet" href="https://pingendo.com/assets/bootstrap/bootstrap-4.0.0-beta.1.css" type="text/css"> -->
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/matches/card_details.html.erb
<style type="text/css">

  .deck_container{

  color: white; background-color: #664213; background-image: -ms-repeating-linear-gradient(top, #664213 0%, #996F28 7%, #664213 10%, #996F28 25%, #664213 26%, #996F28 37%, #664213 38%, #996F28 59%, #664213 61%); background-image: -moz-repeating-linear-gradient(top, #664213 0%, #996F28 7%, #664213 10%, #996F28 25%, #664213 26%, #996F28 37%, #664213 38%, #996F28 59%, #664213 61%); background-image: -o-repeating-linear-gradient(top, #664213 0%, #996F28 7%, #664213 10%, #996F28 25%, #664213 26%, #996F28 37%, #664213 38%, #996F28 59%, #664213 61%); background-image: -webkit-repeating-gradient(linear, left top, left bottom, color-stop(0, #664213), color-stop(0.07, #996F28), color-stop(0.1, #664213), color-stop(0.25, #996F28), color-stop(0.26, #664213), color-stop(0.37, #996F28), color-stop(0.38, #664213), color-stop(0.59, #996F28), color-stop(0.61, #664213)); background-image: -webkit-repeating-linear-gradient(top, #664213 0%, #996F28 7%, #664213 10%, #996F28 25%, #664213 26%, #996F28 37%, #664213 38%, #996F28 59%, #664213 61%); background-image: repeating-linear-gradient(To Bottom, #664213 0%, #996F28 7%, #664213 10%, #996F28 25%, #664213 26%, #996F28 37%, #664213 38%, #996F28 59%, #664213 61%); border: outset 5px #996F28; box-shadow: 0 0 4px 1px #737373; border-radius: 3px;
  }

  .deck_heading{

    text-align: left; font-family: Magic; padding-left: 5px; font-size: 20px; text-shadow: 1px 1px 1px black, -1px -1px 1px black, 1px -1px 1px black, -1px 1px 1px black, 0px -1px 1px black, 0px 1px 1px black, -1px 0px 1px black, 1px 0px 1px black, 0 2px 1px black, -1px 3px 1px black, 1px 3px 1px black; line-height: 28px;font-weight: bold;
  }
  .player_heading{

    text-align: center; font-family: Magic; padding-left: 5px; font-size: 20px; text-shadow: 1px 1px 1px black, -1px -1px 1px black, 1px -1px 1px black, -1px 1px 1px black, 0px -1px 1px black, 0px 1px 1px black, -1px 0px 1px black, 1px 0px 1px black, 0 2px 1px black, -1px 3px 1px black, 1px 3px 1px black; line-height: 28px;font-weight: bold;
  }
  .match-img {
    margin-bottom: 20%;
    margin-top: 20%;
    text-align: center;
        /*margin-top: 133%;
    margin-left: 200%;*/
  }
  .video_link {
    margin-top: 10px;
  }

  .winner {
    text-align: center;
    color: green;
  }

  .looser {
    text-align: center;
    color: red;
  }
</style>

<link type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
<div class="container">
  <h2><%= @match.id %></h2>
  <div class="row">
    <% @decks.each_with_index do |(team, team_decks), index| %>
      <div class="col-md-5 deck_container">
        <% if @match.winner_id == team.id %>
          <h2 class='winner'>WINNER </h2>
        <% else %>
          <h2 class='looser'> LOOSER </h2>
        <% end %>
        <div class="row">
          <span class="deck_heading"><%= team.name %></span>
        </div>
        <div class="row">
          <% team_decks.group_by(&:player).each do |player, deck| %>
            <div class="col-md-12">
              <div class="row">
                <span class="player_heading"><%= player.name %></span>
              </div>
              <div class="row"></div>
              <% deck.each do |deck1| %>
                <%= image_tag "/assets/cards/#{deck1.card.name}.png", width: '100px', height: '100px' %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
      <% if index ==0 %>
        <div class="col-md-2 match-img">
        <%= image_tag "/assets/Clan-Battle.png", width: '100px', height: '100px'%>
        <div class="row"></div>
        <%= link_to 'Video Link', @match.video_link, class: "btn btn-primary video_link", target: :_blank %>
      <% end %>
      </div>
    <% end %>
  </div>
    
</div>

app/views/matches/details.html.erb
<header>
  <h1><img src="/images/logo.png"></h1>
</header>
<br/>
<center>
<% @match.teams.each do |team| %>
  <h3> <%= link_to team.name, match_path(@match, team_id: team.id), target: '_blank', style: 'color: white;' %></h3><br/ >
<% end %>
</center>

app/views/matches/show.html.erb
<%#= react_component("App", props: {match: @match.as_json, willStart: (@match.team_ids.first == @team.id), team: @team}, prerender: false) %>
<script>
  window.matchID = <%= @match.id %>
  window.canBanCard = <%= @match.team_ids.first == @team.id %>
  window.canSelectCard = false;
  window.isFirstTeam = <%= @match.team_ids.first == @team.id %>
</script>
<header>
  <h1><img src="/images/logo.png"></h1>
</header>
<div id="root"></div>
<%= javascript_include_tag 'cable' %>
<%= javascript_pack_tag 'application' %>

app/views/welcome/index.html.erb
<%= image_tag asset_path("cs.jpg"), width: '100%' %>